name: Kotlin

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/kotlin.yml"
      - "kotlin/**"
      - "test.sh"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin

    steps:
      - uses: actions/checkout@v4

      - name: Install wdiff
        run: sudo apt-get install -y wdiff

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew installdist

      - name: Test
        run: ../test.sh
